import {E,Q,P,S,table} from './builders.js';
export const exam=E('fa20-mt1','Fall 2020','A. Tal and U. Vazirani',[
Q(1,'Is there a cycle?',undefined,[P('a','DFS certificate','In a directed graph, output a cycle if one exists; otherwise output a source and sink. Give a linear-time algorithm and justify it.',[
S('Watch the DFS stack','Which edge certifies a directed cycle?','Run DFS over all vertices, maintaining active-stack status and parent pointers. A back edge u→v to an active ancestor v closes the tree path v→…→u. Follow parents from u back to v, reverse that sequence, then append edge u→v to output a cycle. A self-loop gives a one-edge cycle.'),
S('Handle the acyclic case','If no back edge appears, how can a source and sink be found?','The graph is a DAG. Reverse finishing order gives a topological ordering; its first vertex has indegree zero and its last has outdegree zero. Return those. An isolated vertex can be both.'),
S('Bound the work','How often are vertices and edges examined?','Once each in DFS; cycle reconstruction visits at most |V| vertices. Topological order construction is also linear. For an empty graph there is no vertex source/sink to return, so the task presumes a nonempty graph.')],'DFS outputs a back-edge cycle, or the first/last vertices of a topological order.','O(|V|+|E|)')],['Return a concrete certificate, not just a yes/no cycle flag.'],[2]),
Q(2,'FFT simplified',undefined,[
P('a','Two-point Fourier matrix','Write the 2×2 Fourier transform matrix and its root of unity in a+bi form.',[
S('Evaluate a linear polynomial','What are the second roots of unity?','1 and −1. Evaluating a+bx gives a+b and a−b, so the transform matrix is [[1,1],[1,−1]]. The generator is −1+0i.')],'H₁=[[1,1],[1,−1]]; root −1+0i.'),
P('b','Four-point block matrix','Hₙ=[[Hₙ₋₁,Hₙ₋₁],[Hₙ₋₁,−Hₙ₋₁]]. Write H₂.',[
S('Expand the blocks','Where do the negative signs go?','Copy H₁ into the top-left, top-right, and bottom-left blocks; negate its entries in the bottom-right block. Rows are [1,1,1,1], [1,−1,1,−1], [1,1,−1,−1], [1,−1,−1,1].','This recursively defined matrix is a Hadamard transform; it is not the ordinary four-point complex Fourier matrix.')],'Rows: [1,1,1,1]; [1,−1,1,−1]; [1,1,−1,−1]; [1,−1,−1,1].','',{key:{gist:'H₂ is the block expansion of H₁.',body:[],...table(['','','',''],[[1,1,1,1],[1,-1,1,-1],[1,1,-1,-1],[1,-1,-1,1]])}}),
P('c','Fast recursive product','For N=2ⁿ, compute Hₙv in O(N log N). Describe the algorithm and analyze runtime.',[
S('Split the vector','Are these contiguous halves or coefficient-parity halves?','Contiguous halves v₁,v₂ match the matrix block structure. Recursively compute a=Hₙ₋₁v₁ and b=Hₙ₋₁v₂.'),
S('Combine the halves','What do the two output blocks equal?','Return [a+b; a−b]. The additions/subtractions cost O(N), so T(N)=2T(N/2)+O(N)=O(N log N). At N=1, return the input.')],'Recurse on both vector halves; combine their transforms as a+b and a−b.','O(N log N)')],['Block structure reduces a dense matrix product to two recursive calls and linear combining.'],[3]),
Q(3,'Booking flights',undefined,[P('a','Cost then number of flights','Positive integer flight prices connect n cities. Find the cheapest s→t itinerary, breaking ties by fewer flights. Give algorithm and correctness.',[
S('Separate the priorities','What weight makes one dollar outweigh every possible hop-count difference?','Replace price cₑ by n·cₑ+1. Run Dijkstra on the resulting positive-weight graph and retain predecessor edges.'),
S('Compare whole paths','What is a path’s new total?','For cost C and h flights, nC+h. An optimal path is simple since weights are positive, so h<n. Integer costs differ by at least one dollar: all cost-C simple routes have encoded weight below n(C+1), while any cost-(C+1) route is at least n(C+1). For equal cost, the h term chooses fewer flights.'),
S('Recover the itinerary','What if the destination is unreachable?','Report no itinerary. Otherwise follow Dijkstra parents and map edges back to their original prices. Construction is linear; binary-heap Dijkstra takes O((n+m)log n).','Integer prices are needed for this scale argument. If prices are arbitrary reals, use lexicographic labels instead.')],'Run Dijkstra with weights n·price+1; compare encoded totals nC+h.','O((n+m) log n)')],['Integer gaps allow a bounded secondary objective to be encoded in one scalar.'],[4,5]),
Q(4,'Netflix similarity',undefined,[P('a','Rank renaming and inversions','Alice and Bob rank all n movies. Count movie pairs they rank in opposite orders in O(n log n), and justify correctness.',[
S('Remove irrelevant names','How can Alice’s ranking become 1,2,…,n?','Build rankA[movie]=its position in Alice’s list. Replace each movie in Bob’s list by rankA[movie]. The example gives Bob’s renamed sequence [2,1,4,3].'),
S('Count disagreements','Which pair of renamed Bob entries is an inversion?','An earlier Bob entry with larger Alice rank. Bob prefers it but Alice prefers the smaller-ranked later one, exactly a disagreement. Renaming is a one-to-one correspondence, so run the standard inversion-counting algorithm.'),
S('Explain the merge count','If the algorithm must be described, how are cross inversions counted?','Recursively count and sort each half. During merge, when the next right value is smaller than the next left value, add the number of unmerged left values. Those are precisely its crossing inversions. Each pair lies within one half or crosses, giving correctness by induction.'),
S('Analyze runtime','What is the total cost including renaming?','Renaming is O(n) using the movie IDs 1…n. Inversion counting satisfies T(n)=2T(n/2)+O(n)=O(n log n). The example has two disagreements, pairs {1,2} and {3,4}.')],'Rename movies by Alice’s rank, then count inversions in Bob’s renamed sequence.','O(n log n)')],['Reduce two orderings to one numeric permutation before counting disagreements.'],[6])]);
