import {E,Q,P,S,T} from './builders.js';
export const exam=E('fa21-mt1','Fall 2021','J. Nelson',[
Q(1,'Antipasti short answers',36,[
P('a','Log of a factorial','Prove log(n!)=Θ(n log n).',[
S('Bound above','How large can each factor in n! be?','At most n, so n!≤nⁿ and log(n!)≤n log n.'),
S('Bound below','What contribution comes from the largest half of the factors?','At least n/2 factors are at least n/2, so log(n!)≥(n/2)log(n/2)=Ω(n log n). Combine the upper and lower bounds.')],'log(n!)=Θ(n log n).'),
P('b.i','Fewest weak-DAG edges','What minimum edge count can a weakly connected n-vertex DAG have? Give a construction.',[
S('Forget directions','What is the minimum for a connected underlying graph?','n−1. A directed chain v₁→…→vₙ is weakly connected and acyclic, attaining the bound.')],'n−1; a directed chain.'),
P('b.ii','Most DAG edges','What maximum edge count can a weakly connected n-vertex DAG have? Give a construction.',[
S('Use a topological order','How many forward vertex pairs exist?','One per unordered pair, for n(n−1)/2 edges. Include every vᵢ→vⱼ with i<j; all edges point forward and the underlying graph is connected.')],'n(n−1)/2; all forward edges in a total order.'),
P('b.iii','Fewest strongly connected edges','What minimum edge count can a strongly connected n-vertex digraph have? Give a construction.',[
S('Require outgoing edges','For n≥2, how many edges are forced by positive outdegree?','At least n. A directed n-cycle attains it and lets every vertex reach every other. For n=1, the loop-free one-vertex graph needs zero edges.')],'n for n≥2; a directed cycle.'),
P('b.iv','Most strongly connected edges','What maximum edge count is possible under the exam’s “at most one edge between two vertices” wording?',[
S('Resolve the convention','Are opposite directed edges both permitted?','The wording is ambiguous. If both directions are allowed, the complete bidirected graph has n(n−1) edges and is strongly connected. If only one direction per unordered pair is allowed, the bound is n(n−1)/2.'),
S('Give an oriented construction','How can an ordered complete graph become strongly connected?','For n≥3, start with all i→j for i<j, then reverse edge 1→n to n→1. The cycle 1→2→…→n→1 connects all vertices strongly; all other forward edges remain. Both conventions were accepted in the key.')],'n(n−1) if antiparallel arcs are allowed; n(n−1)/2 for oriented simple graphs with n≥3.'),
P('c','Sparse Dijkstra representation','For |E|=o(|V|²), should Dijkstra use adjacency lists or an adjacency matrix? Explain.',[
S('Count neighbor scanning','How expensive is enumerating one vertex’s outgoing edges?','A list takes O(outdegree); a matrix row takes O(|V|), including many absent edges. Over all vertices, lists scan O(|E|), matrices O(|V|²). Lists are preferable in a sparse graph, with the usual heap-based implementation.')],'Adjacency lists avoid scanning absent edges.'),
P('d','Repeated FFT coefficients','How can you roughly halve FFT work on (a₀,a₀,a₁,a₁,a₂,a₂,…)?',[
S('Compare parity subproblems','What are the even and odd coefficient vectors?','Both are (a₀,a₁,a₂,…). Compute their FFT once and reuse it for both halves, then do the usual twiddle-factor butterfly combine. Avoid doing two identical recursive transforms.')],'Compute the identical even/odd transform once and reuse it.'),
T('e','Bounded-edge paths in MSTs','If a graph has an s→t path using only edge weights≤M, must some MST have such a path?',true,'In fact every MST does. If its s→t tree path had edge e>M, removing e creates an s/t-separating cut. The promised path supplies a crossing edge e′≤M. Replacing e with e′ yields a cheaper spanning tree, contradiction.')],['Cuts provide exchange certificates, including for bottleneck paths.'],[1,2,3]),
Q(2,'Chicken-wing tiling',20,[P('a','One missing square','Tile a power-of-two n×n board, excluding one specified square, with nonoverlapping L-shaped trominoes. Give algorithm, proof and runtime.',[
S('Create four valid subproblems','After dividing into quadrants, how can each have one unavailable square?','The quadrant with the true hole keeps it. Place one central L-tromino covering the central corner of each other quadrant. Treat those three occupied squares as each subproblem’s unavailable square.'),
S('Recurse and prove','What is the base case and induction step?','For a 2×2 board, fill its three available squares with one tromino. For a larger board, each quadrant is a smaller board with exactly one unavailable square, so by induction it can be tiled. Quadrants are disjoint, and their tiles avoid the central tromino. Everything except the true hole is covered once.'),
S('Count output work','What is the recurrence in the side length?','T(n)=4T(n/2)+O(1)=Θ(n²). There are (n²−1)/3 tiles to output, so this is optimal up to constants. Pass quadrant boundaries rather than copying an n² array at each call.','Do not recurse on four hole-free quadrants: each recursive instance must satisfy the one-hole assumption.')],'Place one central tromino to create three artificial holes, then recurse on all four quadrants.','Θ(n²)')],['Arrange the combine step so every recursive subproblem has the required form.'],[4,5,6]),
Q(3,'When the levee breaks',18,[P('a','Reverse-time connectivity','m roads flood at distinct times forming a permutation of 1…m. Output Aᵢ, the number of components after the road flooding at time i is removed; analyze runtime.',[
S('Turn deletions into insertions','What graph exists after all m flood events?','No edges, so n singleton components. Build an array T with T[tₑ]=e in O(m), using the fact that flood times are a permutation.'),
S('Record before undoing','What order keeps Aᵢ aligned with “after event i”?','For i=m down to 1, first store Aᵢ=current component count. Then undo event i by inserting T[i]. If its endpoints are in different union–find components, union them and decrement the count. Otherwise the count is unchanged.'),
S('Analyze all operations','Is comparison sorting needed?','No. Indexed placement is linear. Initializing vertices costs O(n), and O(m) union/find operations take O(mα(n)) amortized with rank and path compression. Total O(n+mα(n)).','Store Aᵢ before reinserting edge i; storing after gives the component count before that flood.')],'Process flood events backward with union–find, recording the count before each reinsert.','O(n+mα(n))')],['Offline deletion problems often become simple insertion problems when time is reversed.'],[7,8]),
Q(4,'String matching with wildcards',26,[
P('a','Binary exact matching','For binary pattern P of length m and text T of length n≥m, find all exact matches in O(n log n).',[
S('Encode agreement','Why map 0→(1,0) and 1→(0,1)?','Their dot product is 1 for equal bits and 0 for unequal bits. Encode both strings as doubled-length vectors.'),
S('Correlate every shift','How can all alignment scores be obtained at once?','Reverse the encoded pattern, multiply it with encoded text using FFT, and read only shifts aligned to original characters, at even encoded offsets. A full window matches iff its dot product equals m. The product coefficient for original start j is 2j+2m−1.')],'One-hot encode, FFT-correlate, and report full windows with score m.','O(n log n)'),
P('b','Allow ten percent errors','Find binary matches with at most 10% mismatched positions.',[
S('Reuse the match count','How many agreements does the correlation return?','Exactly the number of equal characters at that shift. Report scores at least ⌈0.9m⌉, equivalently mismatches≤⌊0.1m⌋. Use only complete aligned windows.')],'Report correlation scores≥⌈0.9m⌉.','O(n log n)'),
P('c','Short-pattern speedup','Improve binary exact matching to O(n log m).',[
S('Cover windows by blocks','How can length-m matches crossing a block boundary be retained?','Process text blocks of length at most 2m starting at 0,m,2m,… . Consecutive blocks overlap by m, so every full pattern window belongs to a block. Only emit starts in each block’s first m positions to avoid duplicates.'),
S('Add block costs','What total work results?','O(n/m) FFT problems of size O(m), each costing O(m log m), yield O(n log m). Handle m=1 directly in O(n); uniformly the bound is O(n log(m+1)).')],'Use overlapping 2m-character text blocks and correlate the pattern within each.','O(n log(m+1))'),
P('d','General alphabet','Find exact matches over numerical alphabet 0…s−1 in O(n log n), with no multiplicative dependence on s.',[
S('Use a nonnegative mismatch score','When is Σᵢ(Pᵢ−Tⱼ₊ᵢ)² zero?','Exactly when every position matches. All squared differences are nonnegative, so no mismatches can cancel.'),
S('Expand and compute','Which terms require convolution?','Score(j)=ΣPᵢ²+ΣTⱼ₊ᵢ²−2ΣPᵢTⱼ₊ᵢ. The first term is a constant; sliding text-square sums use prefix sums; the cross term is one FFT correlation. Report zero scores.','Keep the −2 cross-term factor; one printed formula in the key omits it. The exam assumes constant-time arithmetic regardless of symbol magnitude.')],'Use square-difference scores with one correlation and prefix sums.','O(n log n)'),
P('e','Wildcard exact matching','Now either string may contain a wildcard matching any one character. Find all exact compatible windows in O(n log n).',[
S('Give wildcards value zero','How can ordinary alphabet zero be kept distinct?','Map ordinary character a to a+1, making every concrete symbol positive; map a wildcard to 0. Pair compatibility is equivalent to ab(a−b)²=0.'),
S('Expand the score','What correlations compute the sum over a window?','ab(a−b)²=a³b−2a²b²+ab³. Compute three correlations: P³ with T, P² with T², and P with T³, combining as first−2second+third. Every summand is nonnegative and vanishes for equality or a wildcard.'),
S('Read valid matches','When should a window be reported?','Report full windows with combined score zero. A wildcard contributes zero regardless of the other character, and unequal positive concrete symbols contribute strictly positive score. Three FFT products still cost O(n log n).')],'Use zero-coded wildcards and the score Σab(a−b)², computed by three FFT correlations.','O(n log n)')],['A nonnegative mismatch polynomial allows FFT scores without cancellation.'],[9,10])]);
