import {E,Q,P,S,T,table} from './builders.js';
export const exam=E('fa22-mt1','Fall 2022','J. Demmel and J. Nelson',[
Q(1,'Big-O and recurrences',10,[
T('1','Polynomial powers','Is n⁷⁰=O(n¹⁷⁰)?',true,'n⁷⁰/n¹⁷⁰=n⁻¹⁰⁰ tends to zero.'),
T('2','Logarithms of powers','Is log(n¹⁷⁰)=O(log(n⁷⁰))?',true,'These are 170log n and 70log n, differing by a constant factor.'),
T('3','Exponential bases','Is 170ⁿ=O(70ⁿ)?',false,'The ratio (170/70)ⁿ grows without bound; changing an exponential base is not a constant-factor change.'),
T('4','Sum of exponentials','Is 70ⁿ+170ⁿ=O(240ⁿ)?',true,'Both summands are at most 240ⁿ, so their sum is at most 2·240ⁿ.'),
P('5','Many recursive calls','Give the tightest upper bound for T(n)=170T(n/70)+O(n).',[
S('Compare tree and combine','What is the critical exponent?','log₇₀170>1. The leaves dominate the linear toll, giving O(n<sup>log₇₀170</sup>) with constant base cases.')],'O(n<sup>log₇₀170</sup>).'),
P('6','Fewer recursive calls','Give the tightest upper bound for T(n)=70T(n/170)+O(n).',[
S('Compare exponents','Is log₁₇₀70 greater or less than one?','Less than one. The O(n) root/combine toll dominates; costs shrink by 70/170 per level. Upper bound O(n).')],'O(n).'),
P('7','A decrement recurrence','T(n)=T(n−1)+2T(n−2), T(1)=1,T(2)=2. Find the tightest bound.',[
S('Try an exponential','What equation does T(n)=rⁿ suggest?','r²=r+2, whose roots are 2 and −1.'),
S('Use the initial values','Can you verify an exact formula?','T(n)=2ⁿ⁻¹ fits both bases and the recurrence: 2ⁿ⁻²+2·2ⁿ⁻³=2ⁿ⁻¹. Induction proves it, giving Θ(2ⁿ).')],'T(n)=2ⁿ⁻¹=Θ(2ⁿ).')],['Distinguish a constant multiplier from an exponential base.'],[2,3]),
Q(2,'Parth’s paths',7,[
P('1','Five Dijkstra iterations','Run five iterations from C, alphabetically breaking ties. Keep settled distances in the table as instructed.',[
S('First two vertices','What improves after C and A?','C gives A=7,E=17. A gives B=11,D=16,F=18. C and A keep their settled values in this question’s table.'),
S('Next relaxations','How do B,E,G change the frontier?','B improves D to 14,E to 12,G to 13. E improves F to 15. G gives no further improvement. Pop order C,A,B,E,G.')],'C,A,B,E,G are the first five popped vertices.','',{key:{gist:'Final row after five iterations: A7,B11,C0,D14,E12,F15,G13.',body:[],...table(['Iteration','Popped','A','B','C','D','E','F','G'],[[1,'C',7,'∞',0,'∞',17,'∞','∞'],[2,'A',7,11,0,16,17,18,'∞'],[3,'B',7,11,0,14,12,18,13],[4,'E',7,11,0,14,12,15,13],[5,'G',7,11,0,14,12,15,13]])}}),
P('2','Strong components','Find SCCs in alphabetical order in the source graph.',[
S('Use directions','Does an undirected-looking connection suffice?','No. Follow directed routes both ways. A,C,E are mutually reachable; B,D,G are mutually reachable; F cannot return to either group. The ordered SCCs are {A,C,E},{B,D,G},{F}.')],'{A,C,E}, {B,D,G}, {F}.')],['Follow the exam’s convention for settled entries in trace tables.'],[4,5,6]),
Q(3,'Guess the number',8,[
P('1','Known upper bound','Find a positive integer n≤B with O(log B) comparisons that report <,=,>.',[
S('Halve the candidate range','What should each guess be?','Guess the midpoint of the current integer interval [1,B]. Depending on the comparison, retain only the lower or upper half, or stop on equality. Every failed guess halves the range.')],'Binary search [1,B].','O(log B) guesses'),
P('2','No upper bound','Find any positive n in O(log n) guesses without knowing a bound.',[
S('Find a bracket','What guesses grow rapidly but controllably?','Try 1,2,4,8,… until one equals or exceeds n. If it exceeds, n lies between the previous and current powers of two.'),
S('Search the bracket','How many guesses do the two phases take?','O(log n) doublings and O(log n) binary-search guesses. The upper endpoint is less than 2n, so the bracket search has the same logarithmic order.')],'Exponential search for a bracket, then binary search.','O(log n) guesses')],['Doubling finds a missing scale before binary search.'],[7,8]),
Q(4,'Pairing pears',8,[P('a','Adjacent pairing and exchange','The 2N pear positions are already sorted and distinct. Pair every pear once to minimize total pair distance; prove correctness by exchange.',[
S('Choose the first pair','Which partner should the leftmost pear have?','The second-leftmost pear. Then repeat on the remaining sorted positions, pairing (x₁,x₂),(x₃,x₄),….'),
S('Repair a disagreement','If leftmost a and next b instead have partners c,d, how does swapping help?','Both c,d are to the right of b. Old cost c−a+d−b; new cost b−a+|c−d|. The decrease is 2(min(c,d)−b)>0. Thus every optimum must pair a,b, and induction handles the rest.','The input is already sorted, so pairing takes O(N); the key’s extra sorting cost is unnecessary here.')],'Pair consecutive sorted positions; any alternative first pair can be exchanged for a strictly cheaper one.','O(N) on the already sorted input')],['Use the two leftmost positions to localize an exchange argument.'],[9,10]),
Q(5,'Maximum sliding dot product',10,[
P('1','Small example','A=[1,4,2,5,1], B=[2,−1]. What is the maximum length-two window dot product?',[
S('Check every window','What are the four dot products?','2·1−4=−2; 2·4−2=6; 2·2−5=−1; 2·5−1=9. Maximum 9.')],'9.'),
P('2','Convolution algorithm','A has length n, B has length m with log n<m<n. Find the largest dot product with a full length-m A-window; prove correctness and analyze runtime.',[
S('Reverse the short vector','How can convolution align corresponding positions?','With zero-based indices, encode A normally and reverse B: Rⱼ=B<sub>m−1−j</sub>. Multiply their coefficient polynomials by FFT.'),
S('Read the valid range','Which product coefficient corresponds to the window starting at s?','Coefficient s+m−1 is Σⱼ₌₀<sup>m−1</sup>A<sub>s+j</sub>Bⱼ. Scan indices m−1 through n−1 and take their maximum. These are exactly the n−m+1 complete windows; other coefficients represent partial overlap.'),
S('Analyze the speedup','Why is O(n log n) faster than O(nm) under the hypothesis?','The product length is O(n), so FFT costs O(n log n), with a linear scan. Since m>log n, this meets the intended improvement; if m is only Θ(log n), the two bounds can be the same asymptotic order, so a strict little-o improvement needs m=ω(log n).')],'Reverse B, convolve with A, and maximize coefficients m−1…n−1.','O(n log n)')],['Correlation is convolution with one input reversed; scan only full overlaps.'],[11,12]),
Q(6,'Igloo: opening doors',7,[P('a','Connect every room','Doors between adjacent rooms cost energy to open once and stay open. Starting in the upper-left room, visit every room with minimum total opening cost; justify correctness.',[
S('Separate opening from walking','Do repeated visits pay again?','No. Represent rooms by vertices and doors by nonnegative-weight edges. The doors opened by any successful walk form a connected spanning subgraph.'),
S('Remove unnecessary cycles','What cheapest structure still permits all rooms to be visited?','A spanning tree suffices: traverse it from the starting room, reusing open doors freely. Any connected subgraph contains a spanning tree no more expensive, so an MST is optimal. Output its total edge cost; the ending room is unrestricted.')],'Compute an MST of the room-door graph and sum its costs.')],['Pay-once connectivity leads to an MST, even if the walk revisits rooms.'],[13,14]),
Q(7,'Igloo: newly connected pairs',10,[P('a','Union–find with sizes','Whenever a door opens, output the number of unordered room pairs newly connected. Require O(log(mn)) time per opening and prove correctness.',[
S('Store component sizes','What state is needed beyond the union–find parents?','A size at each root. Initially each of the mn rooms is a singleton of size 1.'),
S('Count new pairs','What if the endpoints lie in components of sizes a and b?','If roots agree, output 0. Otherwise exactly the a·b cross-component pairs become connected. Output a·b, union the roots, and set the merged size to a+b. Previously internal pairs were already connected.'),
S('Guarantee per-operation time','Which union policy gives logarithmic height?','Union by size or rank without path compression gives height O(log(mn)): a room’s containing tree can double in size only logarithmically often. Two finds, one union, and constant arithmetic meet the worst-case bound.')],'If components differ, output size₁·size₂ and union; otherwise output 0.','O(log(mn)) worst-case per opened door')],['Component summaries let you answer local connectivity updates.'],[15,16]),
Q(8,'Shalin’s shuffles',12,[P('a','Count increasing pairs','A permutation is drawn left to right. Each card scores the number of previously drawn smaller cards. Give a divide-and-conquer score algorithm, proof and runtime.',[
S('Split the score','Which pairs are counted recursively?','Pairs within the left half and within the right half. Recursive calls return each half sorted plus its score.'),
S('Count crossing pairs','While merging, how many left values are smaller than a right value?','Maintain how many left values have already been emitted. When a right value is emitted, add that count to the cross score. All emitted left values are smaller; every remaining left value is larger. Add left score, right score, and cross score.'),
S('Prove and analyze','Are any scored pairs missed or counted twice?','Every pair lies in exactly one of left, right, or crossing categories. Induction proves recursive counts and the merge counts crossings once. Linear merging yields T(n)=2T(n/2)+O(n)=O(n log n).')],'Modified mergesort counts earlier-smaller pairs during merging.','O(n log n)')],['Return a sorted copy along with a divide-and-conquer statistic.'],[17,18]),
Q(9,'Maximize the number',13,[
P('1','Unlimited swaps','With unlimited adjacent swaps, maximize integer n in O(log n) time and analyze runtime.',[
S('Order the digits','What arrangement makes the first differing digit largest?','Sort digits decreasingly. Use ten digit-frequency counters, then output 9s,8s,…,0s. There are d=Θ(log n) digits, so counting and writing are O(d).','You are computing the maximum value, not outputting the potentially quadratic list of adjacent swaps.')],'Counting-sort the digits descending.','O(log n)'),
P('2','One swap example','Maximize 1263 with at most one adjacent swap.',[
S('Compare positions','Which change improves the most significant digit?','Swap 1 and 2, giving 2163. Swapping 2 and 6 yields 1623, and swapping 6 and 3 lowers the number. The leading-digit improvement wins.')],'2163.'),
P('3','Two swaps example','Maximize 1263 with at most two adjacent swaps.',[
S('Bring a reachable digit forward','What is the largest digit within two positions of the front?','6. Move it left twice: 1263→1623→6123. No 6 can be placed earlier than the first position, and no larger digit exists.')],'6123.'),
P('4','A finite swap budget','Give a polynomial-time algorithm in the number of digits and k for the maximum number after at most k adjacent swaps.',[
S('Optimize the first digit','Which digits can reach the front with the current budget?','The first min(k+1,remaining length) digits. Choose the largest among them; if repeated, choose its leftmost occurrence to spend the fewest swaps.'),
S('Fix the prefix','What should happen after bringing that occurrence forward?','Move it to the front, subtract its original zero-based offset from k, fix it, and repeat on the remaining suffix. Preserving the other digits’ order spends only the necessary swaps. Each choice maximizes the earliest undecided digit and leaves the greatest budget among equal choices.'),
S('Implementation cost','Is a simple scan-and-shift implementation polynomial?','Yes: with d digits it uses O(d²) time and O(d) space. Once k=0, append the remaining suffix unchanged.')],'Repeatedly move the largest reachable digit to the next prefix position, taking its leftmost occurrence.','O((log n)²) for a simple implementation')],['For lexicographic maximization, spend the budget on the earliest undecided digit.'],[19,20,21]),
Q(10,'Wilson’s werewolves',15,[P('a','Nearest broken rooms','Players spawn in an unweighted undirected cave. Each goes to the unique nearest broken room. Count villagers ending in a room with at least one werewolf; give runtime.',[
S('Find nearest facilities','Can all broken rooms be BFS sources at once?','Initialize BFS with all broken rooms at distance zero and each owning its own label. When a room is first discovered, inherit its predecessor’s broken-room owner. This finds the nearest broken room for every reachable room.'),
S('Aggregate players','How do multiple players spawning in one room get handled?','Scan all n players. Increment a villager count for their destination owner, or mark that owner as having a werewolf. Sum villager counts over marked owners. The no-ties assumption makes destination labels unambiguous.'),
S('Account for the input','What work is missing if runtime counts only the graph?','Reading/aggregating players takes O(n). Total O(|V|+|E|+n), with initialization/summing over broken rooms absorbed by |V|. If a player cannot reach any broken room, treat them as having no destination rather than assigning an arbitrary owner.')],'Multi-source BFS labels each room’s nearest broken room; aggregate villagers and werewolves by destination.','O(|V|+|E|+n)')],['Nearest-facility BFS is linear, but reading all players still costs time.'],[22,23])]);
