import {E,Q,P,S,T,table} from './builders.js';
export const exam=E('fa23-mt1','Fall 2023','N. Haghtalab and J. Wright',[
Q(1,'Big-O',6,[
T('a','Nested logarithms','Is (log log n)<sup>100</sup>=O((log n)<sup>1/7</sup>)?',true,'Set t=log n. Then (log t)¹⁰⁰ grows more slowly than t¹ᐟ⁷, since fixed log powers lose to positive powers.'),
T('b','Small exponential exponent','Is 2<sup>√(log n)</sup>=O(n<sup>0.003</sup>)?',true,'Write the right side as 2<sup>0.003 log n</sup>. Eventually √(log n)≤0.003 log n; comparing exponents proves the bound.'),
T('c','Squared logarithm exponent','Is 2<sup>(log n)²</sup>=O(n<sup>0.003</sup>)?',false,'Compare exponents (log n)² and 0.003 log n. The former grows faster by an unbounded factor.'),
T('d','Square root exponent','Is 2<sup>√n</sup>=O(n<sup>log n</sup>)?',false,'n<sup>log n</sup>=2<sup>(log n)²</sup>. √n eventually exceeds (log n)², so the left exponential grows faster.'),
T('e','Sublinear combine','If T(n)=2T(n/2)+O(√n), is T(n)=O(n)?',true,'The recursion leaves cost O(n), and the combine costs sum to O(n): level i contributes O(√n·2ⁱᐟ²), a geometric sum dominated by its last level.'),
T('f','Upper bound versus tight bound','If T(n)=2T(n/2)+O(n), must T(n)=Θ(n log n)?',false,'O(n) permits a smaller combine cost such as Θ(1). Then T(n)=Θ(n), so an upper-bound toll alone cannot force a tight Θ(n log n) result.')],['An O bound does not automatically provide a matching lower bound.'],[2]),
Q(2,'A harmonic recurrence',5,[P('a','Recursion-tree proof','Prove T(n)=2T(n/2)+O(n/log n), with T(1)=1, is O(n log log n).',[
S('Price a level','What do 2ⁱ problems of size n/2ⁱ cost together?','O(n/(log n−i)), for i=0,…,log₂n−1. Treat size-one leaves separately so division by log 1 never occurs.'),
S('Change the index','What happens if j=log₂n−i?','The internal-level sum becomes O(n Σⱼ₌₁<sup>log₂n</sup>1/j)=O(n log log n). There are n leaves costing O(n) total, so they do not change the upper bound.','The key writes a constant leaf contribution, but there are n leaves. Include them; the final bound still holds.')],'A harmonic sum over recursion levels gives O(n log log n).','O(n log log n)')],['When denominators change with depth, rewrite the level sum before bounding it.'],[3,4]),
Q(3,'Short answers',10,[
T('1','Swapped Bellman–Ford loops','Does repeatedly relaxing each single edge |V|−1 times before moving to the next edge correctly solve SSSP without negative cycles?',false,'No. On s→a→b, process a→b first: a is ∞, so every repetition does nothing. Later s→a makes a finite, but a→b is never revisited. Passes must cover all edges repeatedly.'),
T('2','Adjacent DFS siblings','In an undirected graph, can adjacent vertices have the same parent in the DFS tree?',false,'Exploring the first sibling would discover the second through their edge before returning to the parent. The second would become its descendant, not a sibling.'),
P('3a','Horn-SAT: remove a true value','The least-model Horn-SAT algorithm returns (a,b,c,d,e)=(T,F,F,T,T). Could (T,F,F,T,F) also satisfy that formula?',[
S('Identify forced truths','Can a true value in the least model become false in another satisfying assignment?','No. Every truth propagated by the Horn algorithm is forced in every model. Setting e=false violates that requirement.')],'Impossible.'),
P('3b','Horn-SAT: add a true value','Could (T,T,F,T,T) also satisfy the same Horn formula?',[
S('Distinguish forced from optional','Is a false value in the least model necessarily false in every model?','No. b may be optional. For example, a formula requiring only a,d,e permits b=true. It is possible, though not guaranteed for every formula.')],'Possible.'),
P('4','Squaring a set','Eight distinct numbers have only four distinct squares. Must they be the eighth roots of unity?',[
S('Find another paired set','What happens with ±1,±2,±3,±4?','There are eight distinct values and just four squares 1,4,9,16. Most are not on the unit circle, so the condition does not force roots of unity.')],'No: {±1,±2,±3,±4} is a counterexample.'),
P('5','Root generators','Besides ω₁=i, which fourth root of unity generates all four roots?',[
S('Check orders','Which powers visit all four roots before repeating?','ω₃=−i has order 4, visiting 1,−i,−1,i. 1 has order 1 and −1 has order 2, so neither generates the full set.')],'ω₃=−i.')],['Least-model truths are forced; false values may be optional.'],[5,6]),
Q(4,'Possible DFS forests',10,[
P('1','Undirected branches','Is source diagram 1 a possible DFS traversal?',[
S('Test its dashed edge','Does it connect separate sibling branches?','Yes, so it would be a cross edge. Undirected DFS has no cross edges: exploring one endpoint discovers the other before that branch can finish.')],'Impossible.'),
P('2','Opposite cross edges','Is source diagram 2 a possible directed DFS traversal?',[
S('Order the branches','Which direction can a cross edge go?','A cross edge can point from a later-discovered branch to an already finished earlier branch. Opposite cross edges between two branches would require each branch to be later than the other, impossible.')],'Impossible.'),
P('3','Choose branch order','Is source diagram 3 a possible directed DFS traversal?',[
S('Schedule the exploration','Which branch should be explored first?','Explore the lower-left vertex first and finish it. Then explore the top-right/top-left branch. Its non-tree edges can now point toward the already finished branch, consistent with DFS.')],'Possible: explore the lower-left branch first.'),
P('4','Tree structure','Is source diagram 4 a possible DFS traversal?',[
S('Check tree edges themselves','Can the bold edges contain a cycle?','No. Discovery edges give each non-root vertex exactly one parent and form a forest. The proposed bold edges do not form a tree/forest.')],'Impossible.'),
P('5','Multiple roots','Is source diagram 5 a possible directed DFS traversal?',[
S('Allow a DFS forest','Must the first root reach every vertex?','No. Explore the right vertex first. After it finishes, a fresh root at the left vertex yields the displayed second tree.')],'Possible: right root first, left root second.')],['Check the forest first, then ancestry and the direction of cross edges.'],[7,8,9]),
Q(5,'Spaceship',10,[P('a','Stack compatible trapezoids','Component i has height 1 and bases aᵢ<bᵢ. It can sit above j iff bᵢ≤aⱼ. Find the maximum height faster than O(n³).',[
S('Recognize intervals','What interval does a trapezoid correspond to?','[aᵢ,bᵢ]. A feasible stack is a set of nonoverlapping width intervals. You can use the reverse version of interval scheduling.'),
S('Scan in one direction','Which width should be maximized for the next lower-to-upper choice?','Sort decreasing aᵢ. Set current width w=∞ and height h=0. When bᵢ≤w, accept the component, increment h, and set w=aᵢ; otherwise skip it. Return h.'),
S('Why the choice is safe','Can a greedy component replace the next optimal component?','Greedy chooses a feasible component with aᵢ at least as large as the optimum’s next aⱼ. Replacing j with i leaves at least as much width for every component above. Thus the remaining optimal stack remains feasible.')],'Sort by decreasing smaller base aᵢ; accept bᵢ≤w and update w=aᵢ.','O(n log n)')],['Interval scheduling can run from either end when the matching greedy rule is used.'],[10,11]),
Q(6,'Karatsuba subproblems',5,[P('a','Split at two digits','List the three top-level Karatsuba products for 5432·6789. Put each smaller operand first and sort by that operand.',[
S('Separate high and low halves','What are a,b,c,d in (100a+b)(100c+d)?','a=54,b=32,c=67,d=89. Compute bd=32·89, ac=54·67, and (a+b)(c+d)=86·156.'),
S('Recover the middle term','Why are only three products needed?','ad+bc=(a+b)(c+d)−ac−bd. The two already computed outer products recover the cross term, replacing a fourth recursive multiplication.')],'32×89; 54×67; 86×156.')],['One sum-product replaces two cross products.'],[12]),
Q(7,'Kruskal trace',6,[P('a','Accepted edge sequence','For each edge of the source graph, state whether it is in Kruskal’s MST and its insertion order.',[
S('Scan weights','Which low edges join new components?','DF(2), DC(7), DB(11). BC(22) is skipped because B and C are already connected through D. BG(24) is next, then DA(27).'),
S('Finish spanning','How does E join?','AB(30) closes a cycle. AE(48) attaches E as the sixth edge. All later edges close cycles. Thus the accepted order is DF,CD,BD,BG,AD,AE; AB,AF,BC,BE,CG,DE are excluded.')],'DF(1st), CD(2nd), BD(3rd), BG(4th), AD(5th), AE(6th); all others excluded.')],['The sort order is not the insertion order: skip cycle-forming edges.'],[13]),
Q(8,'Batched selection',12,[P('a','Split by query rank','Answer m distinct kth-largest queries on n distinct values in O(n log m), using deterministic linear-time selection.',[
S('Balance the queries','Should the pivot be the median value or the median requested rank?','Sort the query ranks and choose their median rank k*. Select the k*th largest value p deterministically. Partition values into R>p and L<p; p answers one query.'),
S('Adjust ranks','Which requests go to which partition?','Ranks below k* recurse in R unchanged. Ranks above k* recurse in L after subtracting |R|+1=k*. Empty query sets stop immediately; one query uses one selection call.'),
S('Sum each level','Why need not data partitions be balanced?','The query counts halve, so depth is O(log m). At a fixed level the data subsets are disjoint and total at most n values, so all selections/partitions cost O(n). Query sorting costs O(m log m)≤O(n log m). For m=1, the bound is O(n); uniformly write O(n log(m+1)).')],'Select the median requested rank, partition, and recurse only on requested sides.','O(n log(m+1))')],['Balance the scarce dimension—here the number of queries.'],[14,15]),
Q(9,'Birthday attendance',12,[
P('a','Probability coefficients','Friend i attends independently with probability pᵢ. Explain how P(x)=∏ᵢ((1−pᵢ)+pᵢx) encodes the attendance distribution.',[
S('Expand one outcome','What does choosing pᵢx from a factor mean?','Friend i attends; choosing 1−pᵢ means absence. The exponent counts attendees, and independence makes the coefficient product the probability of that particular attendance pattern.'),
S('Sum matching exponents','What is the coefficient of xᵐ?','It sums the probabilities of every pattern with exactly m attendees. Therefore [xᵐ]P(x)=Pr(M=m), including m=0.')],'The coefficient of xᵐ is Pr(M=m).'),
P('b','Fast product tree','Compute all coefficients of P in O(n(log n)²).',[
S('Multiply balanced groups','What should the recursive calls return?','Each returns the product polynomial for half the friends. Multiply the two resulting degree-O(n) polynomials using FFT in O(n log n).'),
S('Count levels','What recurrence results?','T(n)=2T(n/2)+O(n log n). There are O(log n) levels, each costing at most O(n log n), so O(n(log n)²). Pad FFT lengths enough to avoid cyclic wraparound.')],'Balanced divide and conquer with FFT at each combine.','O(n(log n)²)')],['Probability-generating functions turn sums of independent counts into polynomial multiplication.'],[16,17,18]),
Q(10,'Unique topological sort',10,[
P('a','Consecutive-edge test','Determine whether a DAG has a unique topological ordering in linear time.',[
S('Find one ordering','What ordering can you get with DFS or indegree elimination?','Compute v₁,…,vₙ in topological order. Check whether edge vᵢ→vᵢ₊₁ exists for every consecutive pair.'),
S('Explain both directions','What happens if one consecutive edge is missing?','Swap that adjacent pair: no edge is reversed, and no longer path can lie between adjacent positions, so a second order exists. If every consecutive edge exists, those edges form a chain requiring exactly this order.')],'Unique iff every consecutive pair in one topological order has a forward edge.'),
P('b','Runtime','Analyze the consecutive-edge test.',[
S('Avoid repeated whole-graph scans','How do you test each pair efficiently?','Store positions, scan each adjacency list once, and mark whether its required consecutive successor occurs. Topological sorting plus the scan is O(n+m).')],'O(n+m).','O(n+m)')],['Adjacent incomparable vertices certify nonuniqueness.'],[19,20]),
Q(11,'Min-max spanning trees',12,[
P('a','MST implies minimum bottleneck','If an MST T had a larger heaviest edge than another spanning tree T′, how would you improve T?',[
S('Cut the heaviest edge','What pieces does removing that edge create?','Two components. T′ must contain an edge e′ crossing this cut. Every T′ edge is lighter than the removed maximum edge e.'),
S('Exchange the edges','Why does T−e+e′ contradict optimality?','It reconnects the components with no cycle, so it is a spanning tree. Its total weight is lower because w(e′)<w(e). Therefore every MST minimizes its heaviest edge.')],'Replace T’s heaviest edge by a lighter T′ edge across its cut.'),
P('b','Converse counterexample','Give a graph with at most four vertices where a min-max tree is not an MST.',[
S('Force a common bottleneck','Can a triangle have edge weights 1,2,2?','Yes. Every spanning tree needs an edge of weight 2, so minimum possible bottleneck is 2. The tree using both weight-2 edges is min-max with total 4; a tree using weights 1 and 2 is an MST with total 3.')],'Triangle weights 1,2,2: bottleneck-optimal tree total 4; MST total 3.')],['Minimizing the largest edge is weaker than minimizing the sum.'],[21,22,23,24]),
Q(12,'Free flights',12,[P('a','Coupon layers','Find a cheapest route from city 1 to city n using at most k free flights. Flight costs are nonnegative.',[
S('Record coupons used','What state distinguishes routes arriving at the same city?','(v,j), where j=0,…,k is the number of free flights used. For each route u→v of cost w, add a same-layer arc of cost w; when j<k, also add (u,j)→(v,j+1) of cost 0.'),
S('Choose the destination','Does “at most k” require ending in layer k?','No. Run Dijkstra from (1,0) and return minⱼ d(n,j). This handles routes with fewer than k edges. Alternatively add zero-cost transitions that discard unused coupons, then target layer k.','The key targets only the last layer without discard arcs; taking the minimum across layers avoids that exact-versus-at-most issue.'),
S('Bound the graph','Can k be capped?','If the destination is reachable, an optimal route can be simple because costs are nonnegative and deleting a cycle never increases payment. So cap k at n−1. There are O((k+1)n) states and O((k+1)m) arcs, giving O((k+1)(m+n)log n).')],'Run Dijkstra on coupon layers and minimize over all destination layers.','O((k+1)(m+n) log n), with k capped at n−1')],['An “at most” resource constraint accepts every feasible terminal state.'],[25,26])]);
