import {E,Q,P,S,T,A,table} from './builders.js';
const dfsRows=[['A',1,16],['B',2,9],['C',3,8],['D',11,14],['E',10,15],['F',5,6],['G',4,7],['H',12,13],['I',17,18],['J',19,20]];
export const exam=E('fa24-mt1','Fall 2024','S. Garg and P. Raghavendra',[
Q(1,'Asymptotic analysis',4,[A([
['2<sup>log n</sup>','n<sup>0.9</sup>',1,'2<sup>log₂n</sup>=n, which grows faster than n⁰·⁹.'],
['n⁴+2ⁿ','n²+3ⁿ',0,'Exponentials dominate both polynomials, and (2/3)ⁿ tends to zero.'],
['(log n)²','n<sup>1/2</sup>',0,'Any fixed positive power of n eventually beats any fixed power of log n.'],
['2n⁴+n²log n','n⁴+10n³',2,'Both leading terms have degree four, so both functions are Θ(n⁴).']
])],['Simplify first; compare the dominant terms.'],[2]),
Q(2,'Runtime analysis',10,[
P('1','Count this call’s prints','what(n) prints n in a loop of lengths n, ⌊3n/4⌋, ⌊(3/4)²n⌋,…, then recursively calls what(⌊n/2⌋) twice. Find B(n), the number of prints of n, and justify it.',[
S('Read the loop bound','Does each inner loop run n times or k times?','It runs k times. k shrinks by a factor of 3/4 each round.'),
S('Sum the series','What bounds n+(3/4)n+(3/4)²n+…?','The first term is n, and the infinite geometric sum is 4n. Floors only reduce later terms. Thus n≤B(n)≤4n, so B(n)=Θ(n).','Do not multiply n by the number of rounds; those rounds have decreasing work.')],'B(n)=Θ(n).'),
P('3','Recurrence and solution','Write and solve the recurrence for the total runtime of what(n).',[
S('Add recursive work','How many half-sized calls are made?','Two. The local loop costs Θ(n), so T(n)=2T(⌊n/2⌋)+Θ(n), with a constant base case.'),
S('Solve the recurrence','What does each recursion level cost?','There are 2ⁱ calls of size n/2ⁱ, so each full level costs Θ(n). There are Θ(log n) levels. Total Θ(n log n).')],'T(n)=2T(n/2)+Θ(n)=Θ(n log n).','Θ(n log n)')],['A shrinking inner loop may be linear even though it has logarithmically many rounds.'],[2,3]),
Q(3,'Connectivity in graphs',8,[
P('1','DFS timestamps','Run DFS on the source graph starting at A; break ties alphabetically and fill pre/post values.',[
S('Follow the call stack','Which vertices are first discovered?','A→B→C→G→F; finish F,G,C,B. Next explore E→D→H, then finish H,D,E,A. Continue the DFS forest at I and J.'),
S('Count both events','When does the clock advance?','Assign one timestamp on entry and another on exit. The clock runs from 1 through 20, including new roots I and J. Compare the completed table below with the call stack.')],'Use one clock for all ten vertices.', '',{key:{gist:'A(1,16), B(2,9), C(3,8), D(11,14), E(10,15), F(5,6), G(4,7), H(12,13), I(17,18), J(19,20).',body:[],...table(['Vertex','pre','post'],dfsRows)}}),
P('2','Classify the edges','Mark every cross edge and back edge in the source graph.',[
S('Use interval relationships','How can timestamps identify an edge’s type?','A back edge points to an ancestor still on the DFS stack. Cross edges go between disjoint DFS intervals. An edge to a finished descendant can instead be forward.'),
S('Apply the rule','Which edges land on ancestors or completed branches?','Back: D→A, G→C, H→D, H→E. Cross: E→B, I→E, I→F, I→H, J→G, J→I, J→F. The remaining non-tree edge B→F is forward.','Finished destination alone does not imply cross: test whether its interval lies inside the source interval.')],'Back: DA, GC, HD, HE. Cross: EB, IE, IF, IH, JG, JI, JF.'),
P('3','SCC output order','List the strongly connected components in the course algorithm’s output order.',[
S('Find mutual reachability','Which groups can travel to every member and back?','The components are {A,D,E,H}, {B}, {C,G}, {F}, {I}, {J}. Contracting these groups produces a DAG.'),
S('Order the components','Does the reversed-graph-first Kosaraju algorithm emit sources or sinks first?','Sinks first: {F}, {C,G}, {B}, {A,D,E,H}, {I}, {J}. This is reverse topological order, following the course’s convention.')],'{F}, {C,G}, {B}, {A,D,E,H}, {I}, {J}.')],['Entry/exit intervals describe DFS ancestry; SCC contraction is a DAG.'],[4,5,6]),
Q(4,'Dijkstra execution',6,[P('a','Trace the priority queue','From S, give the queue immediately before each DeleteMin in the five-vertex source graph.',[
S('Initialize and relax','What changes after removing S?','Start S=0 and all other keys ∞. After S: A=15,B=5,C=12,D=∞.'),
S('Process the next vertices','Which tentative distances improve through B and C?','Remove B=5: C becomes 10. Remove C=10: A becomes 11 and D becomes 20. Remove A=11: D remains 20. Pop order S,B,C,A,D. Removed vertices are absent from the queue, not listed with a final key.')],'Queue rows: (0,∞,∞,∞,∞); (—,15,5,12,∞); (—,15,—,10,∞); (—,11,—,—,20); (—,—,—,—,20).','', {key:{gist:'DeleteMin order S,B,C,A,D.',body:[],...table(['Before pop','S','A','B','C','D'],[[0,0,'∞','∞','∞','∞'],[1,'—',15,5,12,'∞'],[2,'—',15,'—',10,'∞'],[3,'—',11,'—','—',20],[4,'—','—','—','—',20]])}})],['Dijkstra prioritizes complete distance from S, not the last edge weight.'],[7,8]),
Q(5,'MST execution',6,[
P('1','Kruskal edge order','Which are the fourth and fifth edges added by Kruskal in the source graph?',[
S('Sort and skip cycles','What are the early accepted edges?','Accept DE(1), AD(2), CF(3). Skip AE(4), since A,D,E are already connected. DG(5) is accepted fourth, CE(6) fifth.')],'Fourth DG; fifth CE.'),
P('2','Prim edge order','Which are the fourth and fifth edges added by Prim starting at A?',[
S('Track the current tree','Which edges are cheapest across the changing cut?','Start A: choose AD(2), then DE(1), then DG(5). The next crossing edge is EC(6), followed by CF(3).','Prim can add a lighter edge later: it was unavailable across an earlier cut.')],'Fourth CE; fifth CF.'),
P('3','Shortest path tree','Which are the fourth and fifth edges added to Dijkstra’s shortest path tree from A?',[
S('Compare path totals','Why are B and C tied?','After A,D,E,G are settled, B has distance 9 directly from A and C has distance 2+1+6=9 through D,E. Either can be popped next. Their parent edges are AB and EC.')],'AB and CE in either order are the fourth/fifth edges.')],['Kruskal uses global edge weights; Prim uses crossing weights; Dijkstra uses path totals.'],[9]),
Q(6,'Short answers',18,[
P('1','Huffman lengths','Symbols A,B,C,D,E have frequencies 20,40,45,50,80. How many bits do C and E need?',[
S('Merge two minima','What is the sequence of merged weights?','20+40=60; 45+50=95; 60+80=140; 95+140=235. C belongs to the 95 subtree and E to the 140 subtree, each one level below a root child. Both have depth two.')],'C: 2 bits. E: 2 bits.'),
P('2','Guaranteed disconnection','In the shown undirected DFS tree A→B→C→D, D has branches rooted at F and J. What smallest vertex set necessarily disconnects the graph?',[
S('Use the missing cross edges','Can separate DFS branches have edges between them?','No: undirected DFS has no cross edges. But either branch can have a back edge to any ancestor A,B,C,D.'),
S('Block every ancestor detour','Why is deleting only D insufficient?','J’s branch could still connect through A, B, or C. Delete {A,B,C,D} to eliminate all ancestor routes between the J branch and the F branch. Fewer deletions cannot guarantee disconnection without knowing the hidden back edges.')],'{A,B,C,D}.'),
T('3','Equal-weight MST edges','If e₁ and e₂ have the same weight and e₁ belongs to every MST, must e₂ belong to at least one MST?',false,'A bridge of weight 10 is mandatory, while a weight-10 edge in a triangle whose other edges have weights 1 and 2 is excluded from every MST. Equal weight does not imply equal structural role.'),
T('4','Second lightest edge','With distinct weights in a connected simple graph, is the second lightest edge always in the MST?',true,'Kruskal accepts the lightest edge. With only that edge present, the second edge cannot close a cycle in a simple graph, so it is also accepted.'),
P('5','DFS edge counts','A connected undirected graph has n vertices and m edges. How many back and cross edges occur in DFS?',[
S('Subtract the tree','How many edges are not tree edges?','A DFS tree has n−1 edges. Every remaining undirected edge joins an ancestor and a descendant, so there are m−n+1 back edges and zero cross edges. Count an undirected edge once.')],'m−n+1 back edges; 0 cross edges.'),
P('6','Matrix addition','How long does adding two n×n matrices take with constant-time scalar arithmetic?',[
S('Count outputs','How many independent sums must be written?','One for each of n² entries. The direct algorithm is Θ(n²), and producing all n² outputs gives the same lower bound.')],'Θ(n²).','Θ(n²)'),
P('7','Delete an undirected edge','What maximum number of connected components can deleting one edge create in a connected graph?',[
S('Look at a spanning tree','Can more than two pieces be separated by one edge?','If an alternative route exists, connectivity remains. Otherwise the edge is a bridge, and removing it splits the graph into exactly two components. A tree attains two.')],'2 connected components.'),
P('8','Delete a directed edge','What maximum number of SCCs can deleting one edge create in a strongly connected n-vertex digraph?',[
S('Find an extremal example','What happens to a directed cycle?','Delete one edge from a directed n-cycle. The remaining directed path has no way back, so every vertex is its own SCC. n is also the trivial upper bound.')],'n SCCs.'),
T('9','Largest preorder','Can any chosen vertex always receive the largest DFS pre-value by changing traversal order?',false,'In A→B→C→D→B, visiting B while either C or D is unvisited discovers another vertex after B. If C or D is visited first, its traversal discovers B before finishing the cycle. Thus B cannot be last.'),
T('10','Smallest preorder','Can any chosen vertex receive the smallest DFS pre-value by changing traversal order?',true,'Choose that vertex as the first DFS root. Its entry event is first.')],['Use a structural counterexample to disprove an “always” claim.'],[10,11,12,13]),
Q(7,'Fibonacci revisited',12,[
P('1','Cost of simple Fibonacci','Fᵢ has Θ(i) digits. Find and justify the runtime of computing F₁,…,Fₙ by repeated addition.',[
S('Price an addition','Is Fᵢ₋₁+Fᵢ₋₂ constant-time here?','No. It touches Θ(i) digits. Sum Θ(i) over i=3,…,n, obtaining Θ(n²).')],'Θ(n²) digit operations.','Θ(n²)'),
P('3','Faster matrix powering','Use M=[[1,1],[1,0]] and [Fₙ₊₁,Fₙ]ᵀ=Mⁿ⁻¹[1,1]ᵀ to compute Fₙ faster.',[
S('Reuse the half power','How do you calculate Mᵏ without k multiplications?','Recursively compute M<sup>⌊k/2⌋</sup> once, square it, and multiply by M if k is odd. Use identity matrix for exponent zero.'),
S('Charge by bit length','How expensive is a square at exponent k?','Entries have Θ(k) digits. A 2×2 square uses a constant number of scalar products; Karatsuba costs O(k<sup>log₂3</sup>). Thus T(k)=T(k/2)+O(k<sup>log₂3</sup>)=O(k<sup>log₂3</sup>). Read Fₙ from the resulting vector.','Do not claim O(log n) digit operations; the operands grow with n.')],'Exponentiation by squaring with Karatsuba computes Fₙ in O(n<sup>log₂3</sup>) digit operations.','O(n<sup>log₂3</sup>)')],['Repeated squaring reduces the number of products; bit lengths still matter.'],[14,15]),
Q(8,'Four cycles',10,[
P('1','Matrix entry formula','If B=A², write B[i,j] in terms of entries of adjacency matrix A.',[
S('Multiply a row by a column','Which index gets summed out?','B[i,j]=Σₖ A[i,k]A[k,j]. Each nonzero term is a length-two walk i→k→j.')],'B[i,j]=Σₖ A[i,k]A[k,j].'),
P('2','Interpret a positive entry','For i≠j, what does B[i,j]>0 mean in a simple undirected graph?',[
S('Interpret one term','What vertex witnesses positivity?','There is a common neighbor k of i and j, so a two-edge path joins them. In a simple graph k differs from both endpoints.')],'i and j have a common neighbor.'),
P('3','Detect a 4-cycle','Detect a four-cycle in time strictly faster than O(n<sup>2.99</sup>).',[
S('Use opposite corners','How many common neighbors do opposite corners of a four-cycle have?','At least two. If B[i,j]≥2 for i≠j, distinct common neighbors k and ℓ give i→k→j→ℓ→i. Conversely every four-cycle supplies such an entry.'),
S('Compute and scan','Which multiplication algorithm meets the bound?','Compute A² using Strassen in O(n<sup>log₂7</sup>) and scan n² off-diagonal entries. Return yes iff one is at least two.','Diagonal entries count degrees; a large diagonal entry does not establish a four-cycle.')],'A four-cycle exists iff an off-diagonal entry of A² is at least 2.','O(n<sup>log₂7</sup>)')],['Adjacency-matrix powers count walks; choose entries that encode the requested structure.'],[16]),
Q(9,'Bellman–Ford ordering',5,[
P('1','Worst ordering','For the directed grid shown, what minimum number of full Bellman–Ford passes guarantees correctness for the worst edge order?',[
S('Count path edges','How far can an adversarial pass propagate a distance?','If edges are relaxed opposite the path order, a pass may advance only one edge along a path. The longest directed source path in the grid has 10 edges. Ten passes suffice, and weights can make that path shortest so ten are necessary.','The guarantee concerns shortest paths using at most k edges, not paths at least k edges long.')],'10 passes.'),
P('2','Best ordering','For the same DAG, what minimum number of passes guarantees correctness with the best edge order?',[
S('Use the DAG structure','Can every predecessor be processed before its successor?','Yes: relax outgoing edges in vertex topological order. A single pass sends final distances along all paths because every incoming predecessor has already been processed.')],'1 pass.')],['Relaxation order can change convergence speed; topological order solves a DAG in one pass.'],[17]),
Q(10,'Electric cars',20,[
P('1','Build a charging graph','Roads have positive integer drive times. Charging cities offer full (Cfull,Dfull) or partial (Cpartial,Dpartial) recharge, resetting range. Find the quickest s→t route, starting fully charged, in time below Θ(n⁴) independent of numeric ranges.',[
S('Separate driving from charging','What information is enough for one section between recharge stops?','The shortest road travel time d(u,v). Run Dijkstra from s and every charging city; record road paths as well as distances. Any driving section can be replaced by its shortest route without consuming more range.'),
S('Price a section','What is the cost of leaving a charging city u for v?','For each eligible charging option q with d(u,v)≤Dq, use Cq+d(u,v), and choose the minimum. If none fits, omit the arc. The meta-graph vertices are charging cities plus t and a separate initial source state s₀. From s₀, an arc costs d(s,v) whenever d(s,v)≤Dfull; no initial charge fee is added.'),
S('Finish the reduction','How do you turn meta-graph output into an actual route?','Run Dijkstra from s₀ to t. Expand each chosen arc into its stored road path and charge choice. Every real route splits into feasible sections, and every meta-route expands into a feasible real route; the costs agree.','Use a separate initial state if s is a charging city, so later visits to s still pay for recharging. Meta-arcs connect all feasible city pairs, even if no direct road edge joins them.')],'Shortest road sections become meta-arcs priced by recharge plus drive time; run Dijkstra on the charging graph.'),
P('2','Analyze runtime','Analyze the charging-graph algorithm using n cities and m road edges.',[
S('Count searches and arcs','How many Dijkstra runs and meta-arcs can there be?','At most n+1 road searches and O(n²) meta-arcs. With binary heaps, total O(n(m+n) log n+n² log n), hence O(n(m+n) log n), strictly subquartic for simple graphs. With the course’s Fibonacci-heap bound: O(n(m+n log n)).')],'At most n road-source searches dominate construction and the final search.','O(n(m+n) log n), or O(n(m+n log n)) with Fibonacci heaps')],['Recharge boundaries eliminate dependence on battery capacity; distinguish an initial free charge from later charging.'],[18,19,20]),
Q(11,'Median with little communication',20,[P('a','Reveal the rank bit by bit','Alice and Bob each hold 2³⁰ 32-bit integers. Find the combined median using fewer than 4000 communicated bits; local computation is free.',[
S('Track a rank','What rank defines the lower middle value?','There are 2³¹ values total. With one-based ranks, the lower middle rank is 2³⁰; the upper is 2³⁰+1. First find an arbitrary requested rank k.'),
S('Choose the next bit','What counts must they exchange for the current prefix?','Each counts retained values whose next bit is 0 and sends that count. If their sum z≥k, retain the zero-bit values. Otherwise retain one-bit values and replace k by k−z. Repeat for 32 bits; the resulting prefix is the selected value. For signed integers, flip the sign bit before lexicographic bit comparison, then undo it.'),
S('Count communication','How many bits are needed for a count up to 2³⁰?','31 bits, including the endpoint 2³⁰. Two counts per round over 32 rounds cost 1984 bits for one rank. If median means the average of two middle values, run for both ranks: 3968 bits, still below 4000. Both parties then know both values and their average.','The key’s 30-bit count estimate misses the endpoint; using 31-bit counts fixes it without breaking the budget.')],'Select ranks by 32 rounds of prefix counts; 1984 bits per rank, or 3968 for the conventional even-size median.','32 rounds; local computation is unrestricted')],['Communication cost counts transmitted bits, including endpoints and the median convention.'],[21,22])]);
