import {E,Q,P,S,T,A,table} from './builders.js';
export const exam=E('sp20-mt1','Spring 2020','A. Chiesa and J. Nelson',[
Q(1,'Comparing asymptotics',4,[A([
['4<sup>√n</sup>','16<sup>log₂n</sup>',1,'16<sup>log₂n</sup>=2<sup>4log₂n</sup>=n⁴, a polynomial. f=4<sup>√n</sup>=2<sup>2√n</sup> is exponential in √n, and 2√n eventually beats 4log₂n, so f grows faster.'],['(√n+n)(30√n)','n²',0,'Expand f=30n+30n<sup>3/2</sup>=Θ(n<sup>3/2</sup>), smaller than n².'],['n³','n<sup>log₃26</sup>',1,'log₃26<log₃27=3, so the exponent of g is smaller.'],['n<sup>0.001</sup>','log₂n',1,'Every fixed positive polynomial power eventually dominates a logarithm.']])],['Read superscripts carefully: a logarithmic exponent can become a polynomial.'],[1]),
Q(2,'True or false',5,[
T('a','Topological order','Does a DAG need not have a unique topological ordering?',true,'For A→B and A→C, both A,B,C and A,C,B are valid. Independent vertices can swap.'),
T('b','Dijkstra with negatives','Does Dijkstra fail on negative weights because it may not halt, but give correct results if it halts?',false,'The standard settled-vertex algorithm removes finitely many vertices and halts. Negative weights can make a settled distance improve later, so it may halt with wrong answers.'),
T('c','One back edge','If directed DFS finds exactly one back edge, can deleting one edge make the graph a DAG?',true,'Delete that sole back edge. It is not a discovery edge, so the same DFS tree/order is still valid, and no back edges remain. A directed graph is acyclic iff DFS has no back edge.'),
T('d','Converse claim','If deleting one edge makes a digraph acyclic, does every DFS find exactly one back edge?',false,'Use A→B, B→C, C→A, B→D, D→A. Removing A→B breaks both cycles, but DFS from A with C before D has two back edges C→A and D→A.'),
T('e','Two back edges and SCCs','Do two DFS back edges imply at least two nonsingleton SCCs?',false,'The preceding four-vertex graph is one SCC but has two back edges. A single strongly connected region can contain several cycles.')],['An implication need not remain true when its direction is reversed.'],[2,3]),
Q(3,'Recurrences',8,[
P('a','23 thirds','Solve T(n)=23T(n/3)+2n³ with constant base cases.',[
S('Compare exponent thresholds','Is 23 above or below 3³?','Below: 23/27<1. Cubic work shrinks geometrically across levels, so T(n)=Θ(n³).')],'Θ(n³).','Θ(n³)'),
P('b','Cube-root subproblems','Solve T(n)=3T(n<sup>1/3</sup>)+5n with T(3)=3.',[
S('Count a level','What is level i’s local cost?','5·3ⁱ·n<sup>1/3ⁱ</sup>. Repeated cube roots reach constant size after Θ(log log n) levels; the usual T(n/b) Master Theorem does not apply directly.'),
S('Bound everything below the root','How large can the non-root sum be?','Level i has 3ⁱ nodes of size n<sup>1/3ⁱ</sup>, and there are about log log n levels. Below the root, every level costs at most 3<sup>log log n</sup>·5n¹ᐟ³=5(log n)<sup>log₂3</sup>·n¹ᐟ³, so all of them together cost O((log n)<sup>1.6</sup> log log n·n¹ᐟ³)=o(n). The root alone costs 5n, so the total is Θ(n).')],'Θ(n).','Θ(n)'),
P('c','Decrease by three','Solve T(n)=8T(n−3)+1 with T(0)=T(1)=T(2)=1.',[
S('Count expansion depth','How many levels are there and how many leaves?','Θ(n/3) levels with branching factor 8. The geometric sum is Θ(8<sup>⌊n/3⌋</sup>)=Θ(2ⁿ), since the remainder changes only a constant factor.')],'Θ(2ⁿ).','Θ(2ⁿ)'),
P('d','Unequal subproblems','Solve T(n)=T(n/5)+T(4n/5)+3n².',[
S('Guess a quadratic bound','What happens after substituting T(x)≤cx²?','T(n)≤c(n²/25+16n²/25)+3n²=(17c/25+3)n². Choose c≥75/8 and large enough for bases; then this is≤cn².'),
S('Match the lower bound','Why cannot the answer be smaller?','The root alone costs 3n², so T(n)=Ω(n²). Together with the inductive upper bound, T(n)=Θ(n²).')],'Θ(n²).','Θ(n²)')],['Use a tree or substitution when subproblems do not match the ordinary Master Theorem.'],[4,5]),
Q(4,'Dijkstra with negative edges',6,[P('a','Execute the given pseudocode','Run the provided Dijkstra variant from A on the source graph, breaking ties alphabetically. DecreaseKey does nothing for a vertex already removed; distance assignments still occur.',[
S('Follow the actual directions','What comes out of A, and what comes out of C?','A gives B=3,C=−7,D=1. C gives F=1. The weight-4 edge points D→C, so it does not improve D from C. Next pop D (tie with F resolved alphabetically), then F, then E=2.'),
S('Update an already removed vertex','What happens when B=3 is finally processed?','B→D has weight −3 and reduces dist[D] from 1 to 0, but D is already out of the heap and is not processed again. B also sets G=7. Thus E remains 2 instead of the true shortest value 1.'),
S('Separate execution from correctness','What final array does the code return?','A0,B3,C−7,D0,E2,F1,G7. The task asks for the algorithm’s output on this graph, even though its negative-edge assumption is violated.','Do not silently rerun D after its value improves, or replace the requested trace with Bellman–Ford.')],'Returned distances: A0,B3,C−7,D0,E2,F1,G7.','',{key:{gist:'A0, B3, C−7, D0, E2, F1, G7; E is incorrect as a shortest distance.',body:[],...table(['A','B','C','D','E','F','G'],[[0,3,-7,0,2,1,7]])}})],['Trace the supplied algorithm exactly, including how it treats settled vertices.'],[6]),
Q(5,'Factorials',10,[
P('a','A product tree','Multiplying d-bit integers costs O(d<sup>1.59</sup>). Compute n! in O(n<sup>1.59</sup> log<sup>c</sup>n) for some constant c>0.',[
S('Balance the products','Why not multiply 1,2,…,n sequentially?','Repeatedly multiplying a growing accumulator creates many expensive large products. Instead recursively multiply the first half and the second half of an integer interval, then multiply those two results. A single-element interval returns its integer.')],'Use a balanced divide-and-conquer product tree over 1…n.'),
P('b','Bit-complexity analysis','Analyze the product-tree runtime rigorously.',[
S('Bound operand sizes','How many bits can the product of k input factors have?','At most O(k log n), because each input is≤n. Combining a k-factor node costs O((k log n)<sup>1.59</sup>).'),
S('Sum a level','What does level i cost in the balanced tree?','At most 2ⁱ·O(((n/2ⁱ)log n)<sup>1.59</sup>)=O((n log n)<sup>1.59</sup>·2<sup>−0.59i</sup>). This geometric sum is O((n log n)<sup>1.59</sup>). Leaf/output work is smaller. Thus c=1.59 suffices; the key’s looser c=2.59 is also valid.')],'O(n<sup>1.59</sup> log<sup>1.59</sup>n), by summing geometrically decreasing level costs.','O(n<sup>1.59</sup> log<sup>1.59</sup>n)')],['Balance multiplication by the number of factors and charge for their resulting bit lengths.'],[7]),
Q(6,'Fast force computation',10,[
P('a','Encode a signed kernel','Five charges cᵢ lie at positions i. fⱼ=Σᵢ<ⱼcᵢ/(i−j)²−Σᵢ>ⱼcᵢ/(i−j)². Choose p,q so forces appear as product coefficients.',[
S('Reverse the charges','What charge polynomial makes coefficient matching possible?','Use p(x)=c₁x⁴+c₂x³+c₃x²+c₄x+c₅. Its exponents decrease as particle indices increase.'),
S('Encode signs and distances','Which kernel coefficients represent the force from either side?','Use q(x)=1/16+x/9+x²/4+x³−x⁵−x⁶/4−x⁷/9−x⁸/16, with x⁴ coefficient zero. Coefficient x<sup>9−j</sup> of p·q combines cᵢ with kernel index 4+i−j: positive for i<j, zero for i=j, negative for i>j, with magnitude 1/(i−j)².')],'p=c₁x⁴+c₂x³+c₃x²+c₄x+c₅; q=1/16+x/9+x²/4+x³−x⁵−x⁶/4−x⁷/9−x⁸/16.'),
P('b','Find the force coefficient','With those polynomials, which exponent corresponds to f₃?',[
S('Apply the index rule','What is 9−j when j=3?','6. Expanding that coefficient gives c₁/4+c₂−c₄−c₅/4, exactly the force on particle 3.','Coefficient indices depend on the polynomial convention; first derive the rule from your part-a encoding.')],'6, the coefficient of x⁶.')],['Convolution kernels can encode both direction and distance.'],[8]),
Q(7,'Tree matches',20,[
P('a','Optimal paths are edge-disjoint','Pair all 2n vertices of an unweighted tree once, minimizing the sum of pair distances. Prove two optimal pair paths cannot share an edge.',[
S('Cut a shared edge','Where do the two pairs’ four endpoints lie?','Each pair has one endpoint on each side of the edge’s cut. Relabel endpoints a,c on one side and b,d on the other, with original pairs (a,b),(c,d).'),
S('Uncross the pairing','Can you instead pair endpoints on the same side?','Replace them by (a,c),(b,d). The shared intersection of the two tree paths has positive length; the new within-side paths use at most the remaining nonshared portions. At least twice the shared length disappears, so total cost strictly decreases. This contradicts optimality.')],'Uncross two pairs across a shared tree edge to strictly reduce total path length.'),
P('b','Odd-cut characterization','Let L be edges used by an optimal pairing’s paths. Prove e∈L iff deleting e gives two odd-sized components.',[
S('Count cross-cut endpoints','What parity must the number of pairs crossing the cut have?','On either side, internal pairs consume two vertices. Therefore crossing-pair count has the parity of the component’s vertex count. The two sides have the same parity because the tree has 2n vertices.'),
S('Use part a','How many crossing pair paths can use e in an optimum?','At most one, since paths are edge-disjoint. If a side is odd, the crossing count is odd and must be one. If it is even, the count is even and at most one, so it is zero. This proves both directions.')],'Optimal paths use a cut edge exactly when its component sizes are odd.'),
P('c','Compute only the cost','Compute OPT(T) in O(n), using the parity characterization. You need not output a pairing.',[
S('Root the tree','Which side size can be computed cheaply for each edge?','Choose any root. In postorder DFS, compute each subtree size modulo 2: parity(v)=1+Σ parity(child) mod 2.'),
S('Count qualifying edges','How do subtree parities determine the total cost?','For every non-root child v, count its parent edge iff parity(v)=1. The other side is also odd because the total vertex count is even. By parts a,b, the optimal cost is exactly the number of counted edges: each used edge is traversed by one pair path.'),
S('Analyze the work','How many operations are performed per tree edge?','Constantly many. There are 2n vertices and 2n−1 edges, so total O(n) time and O(n) space. Parity arithmetic is constant-sized even in a digit-cost model.')],'Count parent edges whose child subtree has odd size.','O(n)')],['Parity plus edge-disjointness turns an optimization into one tree traversal.'],[9,10,11]),
Q(8,'Trickster negative cycles',22,[
P('a','A harmless negative cycle','Draw a digraph with a negative cycle but a positive well-defined shortest S→T distance.',[
S('Separate relevance from existence','Must every negative cycle affect every destination?','No. Use S→T of weight 1 and a separate cycle X→Y of weight −2, Y→X of weight 1. That cycle has total −1 but is unreachable from S, so the S→T distance is 1. Label all four vertices and all three edges.')],'S→T:1; X→Y:−2; Y→X:1. Shortest S→T distance is 1.'),
P('b.i','Keep one cycle: target B','In the source graph with cycles T,U,V,W, which sole surviving cycles leave S→B distance well-defined?',[
S('Check two reachability tests','Which cycles are both reachable from S and able to reach B?','U and V are relevant, so either makes distance unbounded below. T cannot reach B; W is not reachable from S. Keeping only T or only W leaves the distance well-defined.')],'T and W.'),
P('b.ii','Keep one cycle: target E','Which sole surviving cycles leave S→E distance well-defined?',[
S('Change the target','Which reachable cycle can also reach E?','Only V. T and U cannot reach E; W cannot be reached from S. Thus keeping T,U,or W is harmless for this target.')],'T, U, W.'),
P('b.iii','Bellman–Ford cycle detection','Which sole surviving cycles make Bellman–Ford started at S report a reachable negative cycle?',[
S('Ignore a particular destination','What reachability condition does the standard detector use?','Reachability from S is sufficient. T,U,V are reachable; W is not. A reachable cycle may trigger the detector even when it cannot reach your particular target.')],'T, U, V.'),
T('b.iv','Order-independent tree here','After all negative cycles are removed from this particular graph, is the shortest-path tree independent of edge-relaxation order?',true,'In this instance the shortest routes are unique, so Bellman–Ford must recover the same tree whichever valid relaxation order is used. This is a property of the shown graph; without uniqueness, shortest-path parent trees can differ even though distances agree.'),
P('c.i','Target-specific shortest path','Given arbitrary weighted digraph G and s,t, return their shortest distance if finite, or “no well-defined shortest path” if it is unbounded below. Give a polynomial-time algorithm.',[
S('Filter the graph','Which vertices can matter to an s→t walk?','Compute vertices reachable from s and vertices able to reach t (DFS/BFS from t in the reversed graph). Keep their intersection. If t is unreachable from s, report no route / distance ∞.'),
S('Detect relevant cycles','What does Bellman–Ford on the retained graph tell you?','Every retained vertex lies on some s→t walk. Run Bellman–Ford from s; a still-relaxable edge after |V′|−1 passes proves a reachable negative cycle that can reach t, hence no finite minimum. Otherwise return dist[t].'),
S('Prove the filter is exact','Can a harmful negative cycle have been deleted?','No: a harmful cycle must be reachable from s and reach t, so all its vertices survive. Every original s→t route also survives, preserving all finite candidates.','Do not compare t’s distance after |V| and 2|V| passes: a negative cycle behind a huge access cost may take far longer to influence t numerically.')],'Keep vertices reachable from s and able to reach t; run Bellman–Ford and detect relevant negative cycles.'),
P('c.ii','Runtime','Analyze the filter-and-Bellman–Ford algorithm.',[
S('Combine the phases','Which phase dominates?','Two reachability searches and filtering cost O(|V|+|E|). Bellman–Ford costs O(|V||E|), with one extra edge pass for detection. Uniformly include the linear initialization: O(|V|+|E|+|V||E|).')],'Linear filtering followed by Bellman–Ford.','O(|V|+|E|+|V||E|)')],['A negative cycle destroys s→t distances only when it is reachable from s and can reach t.'],[12,13,14,15,16,17])]);
