import {E,Q,P,S} from './builders.js';
export const exam=E('sp21-mt1','Spring 2021','A. Chiesa and J. Demmel',[
Q(1,'Peachy algorithms',25,[
P('a','Harvest order','Field i needs ℓᵢ>0 liters per day until harvested. Harvest one field per day to minimize total water use.',[
S('Choose a priority','Which fields become most expensive if postponed?','Those with the largest ℓᵢ. Sort decreasing water requirement and harvest in that order. Whether the harvest day itself needs watering changes every schedule by the same constant and does not change the optimum.')],'Harvest in decreasing ℓᵢ.'),
P('b','Exchange proof','Prove the decreasing-water harvest order is optimal.',[
S('Find an inversion','Suppose ℓᵢ<ℓⱼ but i is harvested on day dᵢ<dⱼ. What happens if they swap?','Old water: ℓᵢdᵢ+ℓⱼdⱼ. New: ℓᵢdⱼ+ℓⱼdᵢ. Savings=(ℓⱼ−ℓᵢ)(dⱼ−dᵢ)>0; all other fields are unaffected.'),
S('Conclude optimality','Can an optimum contain such an inversion?','No, since the swap improves it. Removing inversions transforms any order into nonincreasing ℓ without increasing water use; equal requirements can be ordered arbitrarily.')],'Any lower-before-higher inversion can be exchanged for lower water use.'),
P('c','Runtime','Analyze the harvest-order algorithm.',[S('Identify the expensive step','What dominates the work?','Sorting n real requirements is O(n log n); emitting the order is O(n).')],'O(n log n).','O(n log n)')],['Harvest the highest ongoing cost first when every job takes the same time.'],[2]),
Q(2,'Gameshow peak finding',25,[
P('a','Find a local peak','m boxes hold distinct numbers. Find a value greater than its neighbors (one neighbor at an endpoint), opening fewer than O(m) boxes.',[
S('Inspect the middle','What should you do if the middle value is not a peak?','Open the middle box and its existing neighbors. If the middle exceeds both, return it. Otherwise recurse only toward a larger neighbor. For a subarray of size≤3, inspect it directly, retaining the outside-boundary invariant.'),
S('Keep an index range','How do you avoid touching every box?','Recurse on index intervals rather than copying contents. A call opens at most three boxes and discards about half the interval; cached boxes need not be reopened.')],'Binary-search-style peak finding: recurse toward a larger neighbor.'),
P('b','Correctness','Prove that following a larger neighbor always keeps a valid peak.',[
S('Protect subarray endpoints','Could the chosen half’s endpoint be a false peak because of a larger excluded neighbor?','At the new boundary, the retained neighboring value exceeds the excluded middle value. Prior boundaries retain the same protection. Thus a maximum within the retained half is larger than any excluded adjacent value at its boundary and is a peak in the whole array.'),
S('Apply induction','Why does the recursive answer solve the original problem?','Each retained interval contains a whole-array peak and is smaller. The base case checks its few values with protected boundaries; induction proves the recursion returns a valid peak.','The array need not be sorted or unimodal. We seek any local peak, not necessarily the maximum.')],'The larger-neighbor half contains a peak, with boundary comparisons preserving whole-array validity.'),
P('c','Opened-box bound','Analyze the worst-case number of boxes opened.',[S('Write the recurrence','How many boxes and recursive calls occur per level?','O(1) new boxes and one half-sized recursive call: T(m)=T(m/2)+O(1)=O(log m).')],'O(log m).','O(log m) box openings')],['A direction test can guarantee a local optimum without global order.'],[3]),
Q(3,'Greatest roads revisited',25,[
P('a','Fare modulo five','Positive integer one-way bus fares connect n cities via m routes. Find a cheapest San Francisco→New York trip whose total fare is divisible by 5.',[
S('Remember the relevant history','What does one city state fail to distinguish?','Arrivals with different total fares modulo 5. Create states (city,r) for r=0,…,4.'),
S('Lift each route','Where does a fare-p route lead from remainder r?','From (u,r) to (v,(r+p) mod 5), with unchanged cost p. Run Dijkstra from (SF,0) to (NY,0), then map its parents to actual bus routes. If unreachable, report no qualifying trip.')],'Dijkstra on five fare-remainder layers.'),
P('b','Correctness','Prove the remainder-layer reduction preserves feasible trips and costs.',[
S('Lift a real trip','What does the layer at every stop represent?','The accumulated fare modulo 5, by induction over routes. A trip ending with divisible fare lifts to (NY,0) at exactly the same cost.'),
S('Project a state path','Can a transformed path invent a bus ride?','No: every transition was created from an actual ride, with the same fare. Its final remainder zero means the projected trip is feasible. This cost-preserving correspondence lets Dijkstra choose the cheapest valid trip.','A qualifying trip may revisit an original city with a different remainder; do not restrict the original route to simple paths.')],'Feasible original trips and source-to-target layered paths correspond with unchanged costs.'),
P('c','Runtime','Analyze the five-layer algorithm.',[S('Count the expanded graph','How many states and edges are created?','5n states and 5m edges. Construction is O(n+m), and binary-heap Dijkstra costs O((5n+5m)log(5n))=O((n+m)log n).')],'O((n+m) log n).','O((n+m) log n)')],['A fixed-size remainder state adds only a constant factor.'],[4]),
Q(4,'Striped matrices',25,[
P('a','Compact representation','An n×n matrix satisfies Aᵢⱼ=Aᵢ₋₁,ⱼ₋₁. Store it in O(n) space.',[
S('Identify independent entries','What determines one diagonal?','Every diagonal is constant. Store the first row and first column, counting their shared top-left entry once: 2n−1 numbers. Equivalently store d<sub>−(n−1)</sub>,…,d<sub>n−1</sub> with Aᵢⱼ=dᵢ₋ⱼ.')],'Store 2n−1 diagonal values.','O(n) space'),
P('b','Matrix–vector FFT','Multiply the compact striped matrix by an n-vector in O(n log n).',[
S('Use zero-based indices','What convolution coefficient gives output yᵢ=Σⱼdᵢ₋ⱼvⱼ?','Define D(x)=Σₖ₌₀<sup>2n−2</sup>d<sub>k−(n−1)</sub>xᵏ and V(x)=Σⱼ₌₀<sup>n−1</sup>vⱼxʲ. Coefficient n−1+i of D·V is exactly Σⱼdᵢ₋ⱼvⱼ.'),
S('Compute the product','How large a transform is required?','Pad to a power of two at least 3n−2, compute one FFT product, and extract coefficients n−1 through 2n−2. Degrees are O(n), so total O(n log n).')],'Encode the diagonal values, convolve with v, and extract the central n coefficients.','O(n log n)'),
P('c','Matrix–matrix product','Using part b, multiply striped A by an arbitrary n×n matrix M.',[
S('Work column by column','What is column j of AM?','A times column j of M. Run the O(n log n) matrix–vector algorithm on each of n columns and assemble the outputs.')],'Apply part b to each of the n columns.','O(n² log n)'),
P('bonus','Both matrices striped','Give a faster algorithm when M is also striped. The product need not be striped.',[
S('Compare consecutive diagonal entries','How do sums for Cᵢⱼ and Cᵢ₊₁,ⱼ₊₁ overlap?','For C=AM, shift the summation index using both stripe properties. With one-based indices, Cᵢ₊₁,ⱼ₊₁=Cᵢⱼ−AᵢₙMₙⱼ+Aᵢ₊₁,₁M₁,ⱼ₊₁.'),
S('Compute diagonal starts','How much work does each diagonal require?','Compute its first entry in O(n), then each remaining diagonal entry with the O(1) update. There are 2n−1 diagonals and n² outputs, so O(n²) total, optimal for explicit output.','The product is not generally striped: reuse the overlap formula, not a false constant-diagonal assumption.')],'Compute each diagonal’s first dot product, then update along it by adding/removing boundary terms.','O(n²)')],['Diagonal translation symmetry makes matrix–vector products convolutions.'],[5,6])]);
