import {E,Q,P,S} from './builders.js';
export const exam = E('sp26-mt1','Spring 2026','L. Chen and U. Vazirani',[
Q(1,'Mining',25,[
P('a','Choose the minerals','Mineral i has qᵢ pounds available and value vᵢ per pound. Fractions are allowed. Maximize value with a 100-pound capacity; give the algorithm and runtime.',[
S('Choose a priority','Which number tells you the value of one pound?','Sort by decreasing vᵢ. It is already value per pound; do not divide it by qᵢ.'),
S('Fill the bag','What happens when the next mineral does not fit?','Maintain remaining capacity R, initially 100. Take min(qᵢ,R) pounds of each positive-value mineral in sorted order, update R, and stop when R=0 or no positive values remain. Fractions let you fill the last part exactly.')],'Take positive-value minerals in decreasing value per pound, splitting the final portion as needed.','O(n log n)'),
P('b','Exchange proof','Prove the greedy mining algorithm correct with an exchange argument.',[
S('Find a disagreement','Suppose an optimum takes less of a higher-value mineral than greedy. Where is its capacity going?','It either leaves capacity unused or spends some of it on a lower-value mineral. Move a small feasible amount δ into the higher-value mineral.'),
S('Measure the exchange','How much does value change?','Replacing δ pounds of value vⱼ with value vᵢ≥vⱼ changes value by δ(vᵢ−vⱼ)≥0. A strict inequality improves the solution; equality preserves optimality and increases agreement with greedy. Repeat until the optimum matches greedy. This works for real-valued quantities too.','Do not talk only about whole-pound exchanges: quantities may be fractional.')],'Exchanging lower-value weight for available higher-value weight never lowers value; an optimum can be transformed into greedy.')],['Fractional capacity problems can be solved by value density and an exchange argument.'],[3,4]),
Q(2,'Scheduling',25,[P('a','Weighted interval DP','Jobs are sorted by strictly increasing start time sᵢ. Each lasts one hour and pays rᵢ. Give the subproblem, recurrence, base case, output and runtime for maximum nonoverlapping reward.',[
S('Define the state','What prefix of jobs should one table entry summarize?','Let f(i) be maximum reward using jobs 1 through i. Set f(0)=0. Let p(i) be the largest j<i with sⱼ+1≤sᵢ, or 0 if none.'),
S('Split on the last job','What are the two possibilities for job i?','Skip it: f(i−1). Take it: rᵢ+f(p(i)). Therefore f(i)=max(f(i−1), rᵢ+f(p(i))). Fill increasing i and output f(n). Each feasible schedule either contains i or does not, so these cases cover all optima.'),
S('Compute predecessors','Can all p(i) values be found without searching from scratch?','Yes. Because jobs have equal duration and sorted starts, a pointer through earlier jobs advances monotonically. Advance it while sⱼ+1≤sᵢ. It moves at most n times overall. The DP and predecessor computation both take O(n).','Jobs can meet at an endpoint. Use ≤ if finishing exactly when another starts counts as nonoverlapping; the key says “before,” but the usual endpoint convention permits equality.')],'f(0)=0; f(i)=max(f(i−1),rᵢ+f(p(i))); answer f(n).','O(n)')],['A take/skip recurrence becomes linear when predecessor indices move monotonically.'],[6,7]),
Q(3,'One negative edge',25,[
P('a','Two BFS searches','A directed graph has one edge u→v of weight −1; all others have weight +1. Find the shortest s→t distance in linear time using BFS.',[
S('Remove the exception','What graph can BFS handle directly?','Delete u→v to get G′ with all edges +1. Run BFS from s and from v in G′, obtaining dₛ and dᵥ.'),
S('Combine the cases','How do you price a path that uses u→v?','Return min(dₛ(t), dₛ(u)−1+dᵥ(t)). Ignore an expression containing an unreachable distance. Store BFS parents to reconstruct the chosen route. Two searches and graph construction cost O(|V|+|E|).')],'Delete u→v; return min(dₛ(t), dₛ(u)−1+dᵥ(t)).','O(|V|+|E|)'),
P('b','Why the formula works','Justify the two-BFS shortest path algorithm.',[
S('Bound use of the negative edge','Could repeating the exceptional edge help?','For distinct u,v, any cycle containing u→v has at least one +1 edge, so its weight is nonnegative. Cycles can be removed without increasing cost; a shortest simple path uses u→v at most once.'),
S('Prove both cases','What must happen before and after using that edge?','A shortest route avoiding it is measured by dₛ(t). A route using it consists of an s→u route in G′, the −1 edge, and a v→t route in G′. Replacing either segment by its shortest version cannot hurt. If concatenation repeats vertices, remove its nonnegative cycles. The minimum is therefore exact.','A negative self-loop is an exception: it creates a negative cycle. The exam uses the usual simple-graph convention.')],'Every shortest route can avoid the exceptional edge or use it once; BFS computes the optimal ordinary segments.')],['Separate one exceptional edge from a graph on which a standard algorithm works.'],[9,10]),
Q(4,'Decimal to binary',25,[
P('a','Split the digits','Convert an n-digit positive decimal integer into binary faster than the quadratic method. Assume n is a power of two.',[
S('Split the representation','Write 1342 using its two halves.','1342=13·10²+42. In general x=a·10ᵐ+b with m=n/2. Recursively convert a and b, then combine their binary representations using multiplication by binary 10ᵐ and addition.'),
S('Build the power','How can 10ᵐ be formed efficiently in binary?','Start with binary 10 and repeatedly square: 10,10²,10⁴,…,10ᵐ. Use Karatsuba for multiplication. Convert one-digit inputs with a constant-size lookup. A half may have leading zeros; keep its positional width m when combining.')],'Convert the halves recursively; compute binary 10ᵐ; combine a·10ᵐ+b.'),
P('b','Analyze digit work','Prove an O(n<sup>log₂3</sup> log n) bound, or improve it.',[
S('Count bit lengths','How many binary digits does an n-digit decimal number have?','Θ(n), since log₂10 is constant. Thus one Karatsuba combine costs O(nᵖ), p=log₂3.'),
S('Sum the work','If the power is built separately, how many recursive conversion calls remain?','Two. Squaring costs across doubling bit lengths form a geometric series totaling O(nᵖ). So T(n)=2T(n/2)+O(nᵖ)=O(nᵖ), which is even faster than requested. The key’s three-recursion presentation gives 3T(n/2)+O(nᵖ)=O(nᵖ log n).','Squaring log n times does not multiply the final cost by log n: early squarings use much shorter numbers.')],'With separately computed powers: T(n)=2T(n/2)+O(n<sup>log₂3</sup>)=O(n<sup>log₂3</sup>).','O(n<sup>log₂3</sup>), hence also O(n<sup>log₂3</sup> log n)')],['Arithmetic cost depends on operand length; doubling lengths often give a geometric sum.'],[12,13]),
Q(5,'Bonus: a budget on free edges',1,[P('a','Penalized MSTs','Find a minimum-weight spanning tree using at most k edges from a set F of zero-cost free edges. All ordinary weights are nonnegative integers.',[
S('Check feasibility','How few free edges can any spanning tree use?','Delete F and count ordinary-edge connected components c. A spanning tree needs at least c−1 free edges. If the full graph is disconnected or k<c−1, report infeasible. If an ordinary MST of the full graph already uses at most k free edges, return it.'),
S('Introduce a penalty','What happens if every free edge is priced at x≥0?','A tree with ordinary cost W and f free edges costs W+xf. As x increases, an optimal penalized tree can be chosen with nonincreasing f. Use Kruskal while varying the insertion position of the free edges in the sorted ordinary edges; binary search for the transition around k.'),
S('Make transitions one edge at a time','What if equal ordinary weights cause the count to jump past k?','Give ordinary edge i a distinct perturbation εi, with ε=1/((|V|+1)(|E|+1)). Any tree’s total perturbation is less than 1, so it cannot reverse the ordering of distinct integer original costs. Sort the perturbed ordinary weights; test penalties in gaps between them, keeping the free edges as one block. Moving the block past just one ordinary edge changes the accepted free count by at most one, by the Kruskal exchange property. The first position with count≤k therefore has count exactly k, unless the unpenalized optimum was already feasible.','Use gaps and explicit tie-breaking, rather than assuming arbitrary equal-weight Kruskal output visits every count.'),
S('Recover the original objective','Why is a penalized optimum with exactly k free edges optimal for the budget?','If its penalized cost is Z, its original cost is Z−kx. A better tree with f≤k would have penalized cost W′+fx≤W′+kx<Z, a contradiction. Apply this argument to perturbed ordinary costs too. The returned tree minimizes that objective among feasible trees; perturbations totaling less than 1 ensure it also minimizes the original integer objective.')],'Break ordinary-weight ties with sufficiently small perturbations; binary-search the free-edge block’s position in Kruskal order until its tree has k free edges, or return an already feasible unpenalized optimum.','O(|E| log² |V|) for O(log |E|) Kruskal searches in a simple graph')],['A budget constraint can be enforced by a penalty, but feasibility and tie transitions need explicit treatment.'],[15,16])]);
